---
- name: Drain the node
  hosts: k8s_master
  become: true
  become_method: sudo
  gather_facts: false

  vars:
    rebuild: false

  tasks:
    - name: Drain the node
      shell: kubectl drain {{ item }} --delete-local-data --force --ignore-daemonsets
      when: rebuild | bool
      ignore_errors: True
      with_items: "{{ groups['k8s_nodes'] }}"

    - name: Delete node
      shell: kubectl delete node {{ item }}
      when: rebuild | bool
      ignore_errors: True
      with_items: "{{ groups['k8s_nodes'] }}"

- name: Reset k8s on each node
  hosts: k8s_hosts
  become: true
  become_method: sudo
  gather_facts: false

  vars:
    rebuild: false

  tasks:
    - name: Reset
      shell: kubeadm reset -f
      when: rebuild | bool
      ignore_errors: True