---
- name: Prepare kubeadm.conf
  template:
    src: kubeadm.conf.j2
    dest: "{{ ansible_env.HOME }}/kubeadm.conf"

- name: Make sure /etc/kubernetes exists
  file:
    path: /etc/kubernetes
    state: directory

- name: Prepare openstack config file
  template:
    src: cloud-config.j2
    dest: /etc/kubernetes/cloud-config

- name: Verify if k8s is already up and running
  raw: kubectl get node
  register: k8s_is_running
  ignore_errors: True

- name: Initialize k8s master node
  block:
    - name: restart kubelet service
      systemd:
        state: restarted
        daemon_reload: yes
        name: kubelet
    - name: Init master
      shell: kubeadm init --config {{ ansible_env.HOME }}/kubeadm.conf
      register: kubeadm_init
    - fail:
        msg: "kubeadm init command failed."
      when: kubeadm_init.stdout.find ("kubeadm join") == -1
    - name: Prepare kube config
      shell: mkdir -p {{ item }}/.kube && cp -a /etc/kubernetes/admin.conf {{ item }}/.kube/config && chmod 755 {{ item }}/.kube/config
      loop:
        - "{{ ansible_env.HOME }}"
        - /home/ubuntu
  when: k8s_is_running.rc != 0

- name: Allow pod on master
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-
  when: allow_pod_on_master|bool

- name: Download calico manifest file if needed
  get_url:
    url: https://docs.projectcalico.org/v3.8/manifests/calico.yaml
    dest: "{{ ansible_env.HOME }}/calico.yaml"
    force: no

- name: Modify the pod cidr in calico manifest file
  replace:
    path: "{{ ansible_env.HOME }}/calico.yaml"
    regexp: '(^.*value: )"192.168.*'
    replace: '\1"{{ pod_ip_range }}"'

- name: Install Calico
  shell: kubectl apply -f {{ ansible_env.HOME }}/calico.yaml
