---
- name: Check if kubelet.conf exists
  stat:
    path: "/etc/kubernetes/kubelet.conf"
  register: kubelet_conf_exists

- name: Join worker node to the cluster
  block:
    - name: Prepare kubeadm.conf
      template:
        src: kubeadm.conf.j2
        dest: "{{ ansible_env.HOME }}/kubeadm.conf"
    - name: Make sure /etc/kubernetes exists
      file:
        path: /etc/kubernetes
        state: directory
    - name: Prepare openstack config file
      template:
        src: cloud-config.j2
        dest: /etc/kubernetes/cloud-config
    - name: restart kubelet service
      systemd:
        state: restarted
        daemon_reload: yes
        name: kubelet
    - name: Join to cluster
      shell: kubeadm join --config {{ ansible_env.HOME }}/kubeadm.conf
      when: bootstrap | bool
  when: not kubelet_conf_exists.stat.exists