---
- name: Make sure /etc/kubernetes exists
  file:
    path: /etc/kubernetes
    state: directory

- name: Prepare openstack config file
  template:
    src: cloud-config.j2
    dest: /etc/kubernetes/cloud-config

- name: Check if kubelet config file needs change
  shell: grep -q "external" /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
  register: check_kubelet
  ignore_errors: True

- name: Modify kubelet arguments
  replace:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '(.*)KUBELET_KUBECONFIG_ARGS=(.*)$'
    replace: '\1KUBELET_KUBECONFIG_ARGS=--cloud-provider=external \2'
  when: check_kubelet.rc != 0

- name: Verify if k8s is already up and running
  raw: kubectl get node
  register: check_kubectl
  ignore_errors: True

- name: Initialize k8s master node
  block:
    - name: restart kubelet service
      systemd:
        state: restarted
        daemon_reload: yes
        name: kubelet
    # JoinConfiguration does not support --experimental-control-plane and --certificate-key yet in 1.14 (even not in 1.15)
    - name: Join master node
      shell: kubeadm join {{ lb_address }}:6443 --token 9a08jv.c0izixklcxtmnze7 --discovery-token-unsafe-skip-ca-verification --experimental-control-plane --certificate-key {{ hostvars[groups['k8s_master_0'][0]]['certificate_key'] }}
      register: kubeadm_join
    - fail:
        msg: "kubeadm join command failed."
      when: kubeadm_join.stdout.find ("node has joined the cluster") == -1
    - name: Prepare kube config
      shell: mkdir -p {{ item }}/.kube && cp -a /etc/kubernetes/admin.conf {{ item }}/.kube/config && chmod 755 {{ item }}/.kube/config
      loop:
        - "{{ ansible_env.HOME }}"
        - /home/ubuntu
  when: check_kubectl.rc != 0

- name: Allow pod on master
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-
  when: allow_pod_on_master|bool
  ignore_errors: True
