---
- name: Ensure CCM manifests directory
  file: path={{ ansible_env.HOME }}/openstack-cloud-controller-manager state=directory mode=0755

- name: Copy the cloud-config manifest file
  template:
    src: cloud.conf.j2
    dest: "{{ ansible_env.HOME }}/cloud.conf"

- name: Create cloud config secret
  shell: kubectl create secret -n kube-system generic cloud-config --from-file={{ ansible_env.HOME }}/cloud.conf

- name: Copy CCM manifest file
  template:
    src: openstack-cloud-controller-manager.j2
    dest: "{{ ansible_env.HOME }}/openstack-cloud-controller-manager/openstack-cloud-controller-manager.yaml"

- name: Create CCM RBAC manifest file
  copy:
    src: cloud-controller-manager-role-bindings.yaml
    dest: "{{ ansible_env.HOME }}/openstack-cloud-controller-manager/cloud-controller-manager-role-bindings.yaml"

- name: Install CCM
  shell: kubectl apply -f {{ ansible_env.HOME }}/openstack-cloud-controller-manager/

- name: Ensure Cinser CSI plugin directory
  file: path={{ ansible_env.HOME }}/openstack-cinder-csi-plugin state=directory mode=0755

- name: Copy Cinser CSI plugin manifest files
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/openstack-cinder-csi-plugin/{{ item }}"
  loop:
    - cinder-csi-controllerplugin.yaml
    - cinder-csi-controllerplugin-rbac.yaml
    - cinder-csi-nodeplugin.yaml
    - cinder-csi-nodeplugin-rbac.yaml
    - csi-cinder-driver.yaml

- name: Install Cinser CSI plugin
  shell: kubectl apply -f {{ ansible_env.HOME }}/openstack-cinder-csi-plugin/