---
- name: Ensure CCM manifests directory
  file: path={{ ansible_env.HOME }}/openstack-cloud-controller-manager state=directory mode=0755

- name: Copy the CCM manifest files
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_env.HOME }}/openstack-cloud-controller-manager/{{ item }}"
  loop:
    - cloud-config.yaml
    - cloud-controller-manager-role-bindings.yaml
    - openstack-cloud-controller-manager.yaml

- name: Install CCM
  shell: kubectl apply -f {{ ansible_env.HOME }}/openstack-cloud-controller-manager/
